# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('has_combined', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Абоненты',
                'verbose_name': 'Абонент',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.ManyToManyField(related_name='phones', to='subscribers.Person', verbose_name='Абонент')),
            ],
            options={
                'verbose_name_plural': 'Телефоны',
                'verbose_name': 'Телефон',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Область')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='Транслит')),
            ],
            options={
                'verbose_name_plural': 'области',
                'verbose_name': 'Область',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.Region', verbose_name='Область'),
        ),
    ]
