# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='names',
        ),
    ]
