# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 07:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20180206_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='has_combined',
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
