# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_auto_20180207_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='names',
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=models.ManyToManyField(to='subscribers.Phone', verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='phone',
            name='only_for_one',
            field=models.BooleanField(default=True, verbose_name='Используется только одним абонентом?'),
        ),
    ]
